# Generated by Django 5.1.1 on 2024-10-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_watchlist_avg_rating_watchlist_total_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='created_at',
            new_name='created',
        ),
    ]
